base-linux: Fix missing SYS_waitpid syscall on 64bit linux
SYS_waitpid is only available on 32bit Linux. Replacing SYS_waitpid
with SYS_wait4 which is available on both architectures.

This fixes the following compile error:

In file included from .../base-linux/src/core/cpu_session_extension.cc:11:0:
.../base-linux/src/core/include/core_linux_syscalls.h: In function ‘int lx_pollpid()’:
.../base-linux/src/core/include/core_linux_syscalls.h:115:20: error: ‘SYS_waitpid’ was not declared in this scope